apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "main"
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
    - name: lint
      taskRef:
        name: lint
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: tests
      taskRef:
        name: nose
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: args
          value: "-v"
